### ISSUE TITLE
Structured data fields from NT4 do not get decoded

### ISSUE THREAD

**Issue by mjansen4857** [Mechanical-Advantage/AdvantageScope#103]
**Describe the bug**
Not sure if this is intentional or not, but I didn't see anything in the docs mentioning this.

When logging stuff over network tables using the new structured data support, i.e. a Pose2d object, it will show up in AdvantageScope, but will never be decoded or displayed when used.

After logging a Pose2d like so:
```java
Logger.recordOutput("Swerve/Odom", new Pose2d(3.0, 3.0, new Rotation2d()));
```

The pose is showing up as a Pose2d struct properly:
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/9343077/9bc3b9f0-2271-421e-a9ce-3111e0964fa4)

And is recognized as such in AdvantageScope, but will never actually be displayed when used:
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/9343077/d8c0d841-a43b-4491-b47a-9ec707db4548)
Also notice how there is no dropdown for that field to use the translation or rotation components as shown in the docs.

I have not been able to get any of the supported data types to be displayed in any of the tabs over network tables. They do work fine when using a log file.

**Version (required):**
AdvantageScope 3.0.0-beta-4 and AdvantageKit 3.0.0-beta-1.
I also noticed this with AdvantageScope beta 3.

**Comment by jwbonner** [comment]
Turns out the fixes I made to structs for beta 4 missed an obvious problem. This is actually a simple issue with the combination of the non-AdvantageKit NT mode (with AdvantageKit data) and low bandwidth NT mode since AdvantageKit publishes schemas to a different subtable. 72d71109096e773254f1f39b543d4b4aed43a18e fixes this.

The workarounds until the next release would be to switch to either the AdvantageKit NT mode or logging NT mode. If any of the desired data types are published anywhere in NT in addition to AdvantageKit that should also work.
