### ISSUE TITLE
Network table values longer than 8 characters get cut off

### ISSUE THREAD

**Issue by WispySparks** [Mechanical-Advantage/AdvantageScope#138]
**Describe the bug**
On the left side bar that shows network tables if the value of a key is longer than 8 characters it gets cut off to '...'. Resizing the side bar doesn't seem to help.

**To Reproduce**
1. Connect AdvantageScope to a robot and have a network table key:value pair with a value longer than 8 characters.

**Expected behavior**
I should be able to resize the side bar such that I can see the full names of my values. Or resizing the side bar now should do that but it only helps with the keys not the values.

**Screenshots**
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/101812473/1b7f960a-14a9-46b7-aa4c-660119b6f8ae)

**Version (required):**
Version: 3.0.2
Distributor: WPILib
Platform: win32-x64
Build Date: 1/21/2024, 05:27:07 UTC
Electron: 26.2.1
Chromium: 116.0.5845.188
Node: 18.16.1

**Comment by jwbonner** [comment]
Thanks for the feedback. This was an intentional design decision to avoid cluttering the sidebar, since longer strings are best viewed using a tool like the line graph, table, or console. However, having gotten this suggestion multiple times I think it's reasonable to allow the string to change length based on the sidebar width. The change I just pushed will allow it to vary from 5 to 15 characters. Longer strings aren't practical to view on the sidebar regardless, so you can always use a different visualization if you need more characters.
