### ISSUE TITLE
Metadata does not appear while connected to simulator

### ISSUE THREAD

**Issue by jonahsnider** [Mechanical-Advantage/AdvantageScope#2]
Metadata doesn't appear while connected to the simulator. I haven't tested if this is the case while streaming logs from an actual robot.

Opening the saved `.rlog` file includes the metadata.

**Comment by jonahb55** [comment]
This feature has been missing from AdvantageKit for a while; originally, metadata was only included as part of the first cycle. This meant that any clients which connected wouldn't receive the data. [AdvantageKit v1.7.1](https://github.com/Mechanical-Advantage/AdvantageKit/releases/tag/v1.7.1) changes this behavior so that metadata is included in all cycles. This will not increase the size of the log files, since only changes in fields are recorded (and the metadata isn't allowed to change). The only difference is that the metadata will be included when data is sent to a new client.

This change is also compatible with older versions of Advantage Scope ([v1.16.2](https://github.com/Mechanical-Advantage/AdvantageScope/releases/tag/v1.16.2) is not required).
