### ISSUE TITLE
Metadata with slashes in its key is displayed as `undefined` in "Real" column

### ISSUE THREAD

**Issue by jonahsnider** [Mechanical-Advantage/AdvantageScope#3]
```java
Logger.getInstance().recordMetadata("ProjectName", "RapidReact");
Logger.getInstance().recordMetadata("Constants/TargetRobot", Constants.getRobot().toString());
Logger.getInstance().recordMetadata("Constants/Env", Constants.ENV.toString());
Logger.getInstance().recordMetadata("Constants/Mode", Constants.getMode().toString());
Logger.getInstance()
    .recordMetadata("Constants/PeriodSeconds", Double.toString(Constants.PERIOD_SECONDS));
```

![Advantage Scope screenshot](https://user-images.githubusercontent.com/7608555/157185004-58041f37-5290-4492-b329-3494138824e8.png)

**Comment by jonahb55** [comment]
This is because metadata is recorded as normal fields under the "RealMetadata" and "ReplayMetadata" tables. Advantage Scope hides these tables in the side bar but organizes them under the metadata tab. It wasn't properly searching those fields recursively, since the slash creates a subtable. This is now fixed in [Advantage Scope v1.16.2](https://github.com/Mechanical-Advantage/AdvantageScope/releases/tag/v1.16.2).
