### ISSUE TITLE
[REQUEST] Set Odometry and 3D Field alliance color from network tables

### ISSUE THREAD

**Issue by mjansen4857** [Mechanical-Advantage/AdvantageScope#33]
It would be nice to have the option to set the alliance color of the odometry and 3d field tabs based on a value from network tables. For instance, the `IsRedAlliance` boolean in the `FMSInfo` table. Then we would not need to manually choose the correct alliance color when viewing logs after a match.

**Comment by jwbonner** [comment]
This is a little tricky this year because teams may wish to fix the origin to one alliance even when the displayed color on the bumpers changes. Below are some screenshots of what I came up with. For the odometry tab the bumper color and origin can be set independently to auto, blue, or red (with auto bumpers and blue origin as the default). For the 3D field the alliance color is explicitly "origin" (since the bumpers on the models don't change) and has the same options for auto, blue, or red with blue as the default.

<img width="469" alt="Screen Shot 2023-01-28 at 12 27 52 PM" src="https://user-images.githubusercontent.com/47046556/215282261-32a36c3f-4afd-4f72-a983-eebad4ac8f8e.png">
<img width="447" alt="Screen Shot 2023-01-28 at 12 34 59 PM" src="https://user-images.githubusercontent.com/47046556/215282252-5045ecbe-b90f-4351-b5a1-9e9ffd978bf8.png">
