### ISSUE TITLE
Add custom / more modern icons for telemetry pages

### ISSUE THREAD

**Issue by srimanachanta** [Mechanical-Advantage/AdvantageScope#44]
The current emojis make the application seem unprofessional. Using more specific icons / custom-made ones would look better. Obviously, this requires those icons, and I can't draw lol.

**Comment by jwbonner** [comment]
The whole purpose of the emojis is to be fun, which I think is perfectly appropriate in a tool designed for students. Even some professional tools like GitHub use emojis extensively ([example](https://github.com/github)) because it makes them feel more friendly. I don't think there's an issue with the current design.

**Comment by srimanachanta** [comment]
Yeah, I was assuming it was something like that.
