### ISSUE TITLE
High memory usage and freezes.

### ISSUE THREAD

**Issue by lobsterwise** [Mechanical-Advantage/AdvantageScope#62]
Over time AdvantageScope starts to use more and more memory (up to 8G+), which I am assuming is from a memory leak of some sort. It seems to start whenever I open a pop-out window and only stops when the program freezes and goes to black (garbage collection?).

**Comment by jwbonner** [comment]
A few questions to help with debugging:
- What version of AdvantageScope are you running? You can find it under "Help" > "About AdvantageScope" on Linux/Windows or "AdvantageScope" > "About AdvantageScope" on macOS.
- How long does it take for memory usage to increase? Mostly trying to distinguish between a few minutes vs a few hours of runtime, etc.
- Does this happen on a specific tab type? Odometry, 3D Field, Video, Joysticks, Swerve, Mechanism, and Points are all able to create pop-out windows.
- Does it still happen if only one tab is open in the main window? Do any fields need to be displayed or does it start leaking immediately?

**Comment by jwbonner** [comment]
Do you have any fields displayed on the line graph? Based on your description I assume that the memory usage doesn't increase when not interacting with the app, correct?

**Comment by jwbonner** [comment]
Interesting. A quick Google shows that it might be a Chromium bug: https://stackoverflow.com/questions/66802111/what-is-internalnode-in-chrome-heap-profile. Not sure yet if it's related but I'll do some digging to see if this is relevant.

**Comment by jwbonner** [comment]
I've done some more thorough testing, but I still haven't been able to recreate this. Could you send a log file and tab layout where you've seen this occur?

**Comment by jwbonner** [comment]
I've now tried to recreate this on four different laptops (3 Windows + 1 Mac) with no luck. With that in mind, here are some things you might want to try as a next step:

- In case this is because of a Chromium bug that's since been fixed, I ran a build of AdvantageScope to update from Electron 22.3.3 to 23.2.0. You can download the CI artifact [here](https://github.com/Mechanical-Advantage/AdvantageScope/actions/runs/4548827394) once the build finishes. I haven't directly connected the memory leak to the bug I linked earlier, but it's possible there's some other subtle Chromium issue behind this.
- Have you tried opening the log and layout file on other laptops? My failure to recreate it suggests that this may be very device-specific, though still I don't have any idea what would cause it to occur. If it doesn't happen on other laptops, that might narrow the scope of the problem a bit.

**Comment by jwbonner** [comment]
Have you continued to encounter this issue? If not, I'll probably close the issue.

The current dev builds use the latest version of Electron/Chromium, so it's possible that there was a fix for some underlying issue.
