### ISSUE TITLE
Support dashboard definition 

### ISSUE THREAD

**Issue by lidor51** [Mechanical-Advantage/AdvantageScope#95]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Need to open the wanted windows and organize them every them using advantage scope.

**Describe the solution you'd like**
An option to define "a dashboard" - predefined windows settings on the screen. When a user want to create a dashboard, he will organize the desired windows, in the desired location on screen of each.
You can then save/export dashboard.
Useful for two reasons:
A. You can double click on the dasboard file and it'll open all the tiles, with their correct settings, location and size.
B. You can share it between users and machines.

**Comment by jwbonner** [comment]
This is now implemented. That change stores the state of all windows (main windows and popup windows) so they are preserved by default when closing and reopening AdvantageScope. The exported layout file will also include the positions of all of the windows, rather than just the selected one as before.
